[project]
name = "sudoku"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "py-sudoku>=2.0.0",
    "z3-solver>=4.15.4.0",
]
